# Generated by Django 5.1.3 on 2024-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bus/Seat'),
        ),
    ]
